import { createSlice } from "@reduxjs/toolkit";

const products = [
  { 
    id: 1,
    name: "Belimbing", 
    deskripsi: "Belimbing adalah buah yang memiliki bentuk seperti bintang dan memiliki rasa asam.", 
    category: "Buah Lokal", 
    displayPrice: "10.00", 
    price: 1000, 
    rate: '4.5', 
    isFav: false, 
    stok: 50, 
    initialStok: 50, 
    image: "/img/buah_lokal/belimbing.png" },
  { 
    id: 2,
    name: "Dukuh", 
    deskripsi: "Dukuh adalah buah yang memiliki daging buah yang manis dan sering digunakan sebagai campuran dalam berbagai makanan.", 
    category: "Buah Lokal", 
    displayPrice: "12.00", 
    price: 1200, 
    rate: '3.2', 
    isFav: false, 
    stok: 60, 
    initialStok: 60, 
    image: "/img/buah_lokal/dukuh.png" },
  { 
    id: 3,
    name: "Durian", 
    deskripsi: "Durian adalah buah yang memiliki kulit berduri dan daging buah yang beraroma kuat serta memiliki rasa manis.", 
    category: "Buah Lokal", 
    displayPrice: "15.00", 
    price: 1500, 
    rate: '4.8', 
    isFav: false, 
    stok: 70, 
    initialStok: 70, 
    image: "/img/buah_lokal/durian.png" },
  { 
    id: 4,
    name: "Kelapa", 
    deskripsi: "Kelapa adalah buah yang memiliki kulit keras dan daging buah yang berair serta memiliki banyak manfaat.", 
    category: "Buah Lokal", 
    displayPrice: "8.00", 
    price: 800, 
    rate: '4.2', 
    isFav: false, 
    stok: 80, 
    initialStok: 80, 
    image: "/img/buah_lokal/kelapa.png" },
  { 
    id: 5,
    name: "Mangga", 
    deskripsi: "Mangga adalah buah yang memiliki daging buah yang manis serta berwarna kuning atau hijau.", 
    category: "Buah Lokal", 
    displayPrice: "11.00", 
    price: 1100, 
    rate: '3.6', 
    isFav: false, 
    stok: 90, 
    initialStok: 90, 
    image: "/img/buah_lokal/Mangga.png" },
  { 
    id: 6,
    name: "Manggis", 
    deskripsi: "Manggis adalah buah yang memiliki kulit berwarna ungu dan daging buah yang manis serta memiliki biji di dalamnya.", 
    category: "Buah Lokal", 
    displayPrice: "13.00", 
    price: 1300, 
    rate: '4.7', 
    isFav: false, 
    stok: 100, 
    initialStok: 100, 
    image: "/img/buah_lokal/manggis.png" },
  { 
    id: 7,
    name: "Nanas", 
    deskripsi: "Nanas adalah buah yang memiliki rasa asam segar dan sering digunakan dalam berbagai hidangan.", 
    category: "Buah Lokal", 
    displayPrice: "9.00", 
    price: 900, 
    rate: '3.1', 
    isFav: false, 
    stok: 110, 
    initialStok: 110, 
    image: "/img/buah_lokal/Nanas.png" },
  { 
    id: 8,
    name: "Nangka", 
    deskripsi: "Nangka adalah buah yang memiliki daging buah yang manis serta sering digunakan dalam berbagai masakan.", 
    category: "Buah Lokal", 
    displayPrice: "14.00", 
    price: 1400, 
    rate: '4.4', 
    isFav: false, 
    stok: 120, 
    initialStok: 120, 
    image: "/img/buah_lokal/nangka.png" },
  { 
    id: 9,
    name: "Rambutan", 
    deskripsi: "Rambutan adalah buah yang memiliki kulit berduri dan daging buah yang manis serta berwarna merah.", 
    category: "Buah Lokal", 
    displayPrice: "13.00", 
    price: 1300, 
    rate: '3.3', 
    isFav: false, 
    stok: 130, 
    initialStok: 130, 
    image: "/img/buah_lokal/rambutan.png" },
  { 
    id: 10,
    name: "Sirsak", 
    deskripsi: "Sirsak adalah buah yang memiliki daging buah yang berair dan asam serta memiliki biji di dalamnya.", 
    category: "Buah Lokal", 
    displayPrice: "14.00", 
    price: 1400, 
    rate: '4.5', 
    isFav: false, 
    stok: 140, 
    initialStok: 140, 
    image: "/img/buah_lokal/sirsak.png" },
  { 
    id: 11,
    name: "Salak", 
    deskripsi: "Salak adalah buah yang memiliki kulit berduri dan daging buah yang manis serta memiliki biji di dalamnya.", 
    category: "Buah Lokal", 
    displayPrice: "14.00", 
    price: 1400, 
    rate: '4.2', 
    isFav: false, 
    stok: 150, 
    initialStok: 150, 
    image: "/img/buah_lokal/salak.png" },
  { 
    id: 12,
    name: "Alpukat", 
    deskripsi: "Alpukat adalah buah yang memiliki tekstur lembut dan daging buah yang kaya akan lemak sehat.", 
    category: "Buah Import", 
    displayPrice: "16.00", 
    price: 1600, 
    rate: '3.6', 
    isFav: false, 
    stok: 160, 
    initialStok: 160, 
    image: "/img/buah_import/Alpuket.png" },
  { 
    id: 13,
    name: "Anggur", 
    deskripsi: "Anggur adalah buah yang memiliki biji dan terkenal dengan rasa manis dan asamnya.", 
    category: "Buah Import", 
    displayPrice: "18.00", 
    price: 1800, 
    rate: '4.7', 
    isFav: false, 
    stok: 170, 
    initialStok: 170, 
    image: "/img/buah_import/anggur.png" },
  { 
    id: 14,
    name: "Anggur Hijau", 
    deskripsi: "Anggur Hijau adalah varian anggur dengan warna hijau dan memiliki rasa manis.", 
    category: "Buah Import", 
    displayPrice: "20.00", 
    price: 2000, 
    rate: '4.8', 
    isFav: false, 
    stok: 180, 
    initialStok: 180, 
    image: "/img/buah_import/anggur-hijau.png" },
  { 
    id: 15,
    name: "Apel Hijau", 
    deskripsi: "Apel Hijau adalah varian apel yang memiliki daging buah berwarna hijau dan rasa segar.", 
    category: "Buah Import", 
    displayPrice: "22.00", 
    price: 2200, 
    rate: '4.4', 
    isFav: false, 
    stok: 190, 
    initialStok: 190, 
    image: "/img/buah_import/apel-hijau.png" },
  { 
    id: 16,
    name: "Apel Merah", 
    deskripsi: "Apel Merah adalah varian apel yang memiliki daging buah berwarna merah dan rasa manis.", 
    category: "Buah Import", 
    displayPrice: "24.00", 
    price: 2400, 
    rate: '4.6', 
    isFav: false, 
    stok: 200, 
    initialStok: 200, 
    image: "/img/buah_import/apel-merah.png" },
  { 
    id: 17,
    name: "Buah Naga", 
    deskripsi: "Buah Naga adalah buah dengan daging berwarna merah atau putih yang memiliki rasa manis.", 
    category: "Buah Import", 
    displayPrice: "26.00", 
    price: 2600, 
    rate: '4.3', 
    isFav: false, 
    stok: 210, 
    initialStok: 210, 
    image: "/img/buah_import/buah-naga.png" },
  { 
    id: 18,
    name: "Jambu Merah", 
    deskripsi: "Jambu Merah adalah buah dengan daging berwarna merah yang memiliki rasa manis dan segar.", 
    category: "Buah Import", 
    displayPrice: "28.00", 
    price: 2800, 
    rate: '4.5', 
    isFav: false, 
    stok: 220, 
    initialStok: 220, 
    image: "/img/buah_import/jambu-merah.png" },
  { 
    id: 19,
    name: "Jambu Kristal", 
    deskripsi: "Jambu Kristal adalah buah dengan daging berwarna putih bening yang memiliki rasa manis dan renyah.", 
    category: "Buah Import", 
    displayPrice: "30.00", 
    price: 3000, 
    rate: '3.2', 
    isFav: false, 
    stok: 230, 
    initialStok: 230, 
    image: "/img/buah_import/jambu-kristal.png" },
  { 
    id: 20,
    name: "Jeruk", 
    deskripsi: "Jeruk adalah buah yang memiliki kulit tebal dan daging buah berair serta memiliki rasa manis atau asam.", 
    category: "Buah Import", 
    displayPrice: "32.00", 
    price: 3200, 
    rate: '4.7', 
    isFav: false, 
    stok: 240, 
    initialStok: 240, 
    image: "/img/buah_import/jeruk.png" },
  { 
    id: 21,
    name: "Kiwi", 
    deskripsi: "Kiwi adalah buah dengan daging berwarna hijau dan memiliki rasa manis serta asam.", 
    category: "Buah Import", 
    displayPrice: "34.00", 
    price: 3400, 
    rate: '4.6', 
    isFav: false, 
    stok: 250, 
    initialStok: 250, 
    image: "/img/buah_import/kiwi.png" },
  { 
    id: 22,
    name: "Klengkeng", 
    deskripsi: "Klengkeng adalah buah yang memiliki daging buah yang manis dan biji kecil di dalamnya.", 
    category: "Buah Import", 
    displayPrice: "36.00", 
    price: 3600, 
    rate: '4.5', 
    isFav: false, 
    stok: 260, 
    initialStok: 260, 
    image: "/img/buah_import/KLengkeng.png" },
  { 
    id: 23,
    name: "Lemon", 
    deskripsi: "Lemon adalah buah yang memiliki rasa asam segar dan sering digunakan dalam berbagai hidangan dan minuman.", 
    category: "Buah Import", 
    displayPrice: "38.00", 
    price: 3800, 
    rate: '4.3', 
    isFav: false, 
    stok: 270, 
    initialStok: 270, 
    image: "/img/buah_import/lemon.png" },
  { 
    id: 24,
    name: "Melon", 
    deskripsi: "Melon adalah buah yang memiliki daging buah yang manis serta memiliki tekstur lembut dan segar.", 
    category: "Buah Import", 
    displayPrice: "40.00", 
    price: 4000, 
    rate: '4.4', 
    isFav: false, 
    stok: 280, 
    initialStok: 280, 
    image: "/img/buah_import/Melon.png" },
  { 
    id: 25,
    name: "Pepaya", 
    deskripsi: "Pepaya adalah buah yang memiliki daging buah yang manis dan tekstur yang lembut serta memiliki banyak manfaat.", 
    category: "Buah Import", 
    displayPrice: "42.00", 
    price: 4200, 
    rate: '4.2', 
    isFav: false, 
    stok: 290, 
    initialStok: 290, 
    image: "/img/buah_import/Pepaya.png" },
  { 
    id: 26,
    name: "Pisang", 
    deskripsi: "Pisang adalah buah yang memiliki kulit berwarna kuning dan daging buah yang manis serta kaya akan kalium.", 
    category: "Buah Import", 
    displayPrice: "44.00", 
    price: 4400, 
    rate: '4.7', 
    isFav: false, 
    stok: 300, 
    initialStok: 300, 
    image: "/img/buah_import/Pisang.png" },
  { 
    id: 27,
    name: "Semangka", 
    deskripsi: "Semangka adalah buah yang memiliki daging buah yang berair dan manis serta berwarna merah.", 
    category: "Buah Import", 
    displayPrice: "46.00", 
    price: 4600, 
    rate: '4.5', 
    isFav: false, 
    stok: 310, 
    initialStok: 310, 
    image: "/img/buah_import/semangka.png" },
  { 
    id: 28,
    name: "Bawang Bombay", 
    deskripsi: "Bawang Bombay adalah sayuran yang memiliki aroma dan rasa yang khas.", 
    category: "Sayur", 
    displayPrice: "10.00", 
    price: 1000, 
    rate: '3.2', 
    isFav: false, 
    stok: 50, 
    initialStok: 50, 
    image: "/img/sayur/bawang-bombay.jpg" },
  { 
    id: 29,
    name: "Bawang Merah", 
    deskripsi: "Bawang Merah adalah sayuran yang memiliki rasa tajam dan digunakan sebagai bumbu dalam masakan.", 
    category: "Sayur", 
    displayPrice: "12.00", 
    price: 1200, 
    rate: '4.4', 
    isFav: false, 
    stok: 60, 
    initialStok: 60, 
    image: "/img/sayur/bawang-merah.jpg" },
  { 
    id: 30,
    name: "Bawang Putih", 
    deskripsi: "Bawang Putih adalah sayuran yang memiliki rasa dan aroma tajam serta memiliki banyak manfaat kesehatan.", 
    category: "Sayur", 
    displayPrice: "14.00", 
    price: 1400, 
    rate: '4.5', 
    isFav: false, 
    stok: 70, 
    initialStok: 70, 
    image: "/img/sayur/bawang-putih.jpg" },
  { 
    id: 31,
    name: "Bayam", 
    deskripsi: "Bayam adalah sayuran hijau yang kaya akan nutrisi dan sering digunakan dalam masakan.", 
    category: "Sayur", 
    displayPrice: "16.00", 
    price: 1600, 
    rate: '4.3', 
    isFav: false, 
    stok: 80, 
    initialStok: 80, 
    image: "/img/sayur/Bayem.jpg" },
  { 
    id: 32,
    name: "Brokoli", 
    deskripsi: "Brokoli adalah sayuran hijau yang memiliki kandungan gizi tinggi dan sering digunakan dalam hidangan sehat.", 
    category: "Sayur", 
    displayPrice: "18.00", 
    price: 1800, 
    rate: '4.6', 
    isFav: false, 
    stok: 90, 
    initialStok: 90, 
    image: "/img/sayur/Brokoli.jpg" },
  { 
    id: 33,
    name: "Buncis Lokal", 
    deskripsi: "Buncis Lokal adalah sayuran yang memiliki tekstur renyah dan sering digunakan dalam berbagai masakan.", 
    category: "Sayur", 
    displayPrice: "20.00", 
    price: 2000, 
    rate: '3.4', 
    isFav: false, 
    stok: 100, 
    initialStok: 100, 
    image: "/img/sayur/buncis-lokal.jpg" },
  { 
    id: 34,
    name: "Cabe Hijau", 
    deskripsi: "Cabe Hijau adalah sayuran yang memiliki tingkat kepedasan yang sedang dan sering digunakan dalam masakan.", 
    category: "Sayur", 
    displayPrice: "22.00", 
    price: 2200, 
    rate: '4.3', 
    isFav: false, 
    stok: 110, 
    initialStok: 110, 
    image: "/img/sayur/cabe-hijau.jpg" },
  { 
    id: 35,
    name: "Cabe Merah", 
    deskripsi: "Cabe Merah adalah sayuran yang memiliki tingkat kepedasan yang tinggi dan sering digunakan dalam masakan pedas.", 
    category: "Sayur", 
    displayPrice: "24.00", 
    price: 2400, 
    rate: '3.5', 
    isFav: false, 
    stok: 120, 
    initialStok: 120, 
    image: "/img/sayur/cabe-merah.jpg" },
  { 
    id: 36,
    name: "Daun Bawang", 
    deskripsi: "Daun Bawang adalah sayuran yang memiliki aroma khas dan digunakan sebagai bumbu dalam masakan.", 
    category: "Sayur", 
    displayPrice: "26.00", 
    price: 2600, 
    rate: '4.2', 
    isFav: false, 
    stok: 130, 
    initialStok: 130, 
    image: "/img/sayur/daun-bawang.jpg" },
  { 
    id: 37,
    name: "Daun Gingseng", 
    deskripsi: "Daun Gingseng adalah sayuran yang memiliki banyak manfaat kesehatan dan sering digunakan dalam ramuan tradisional.", 
    category: "Sayur", 
    displayPrice: "28.00", 
    price: 2800, 
    rate: '4.7', 
    isFav: false, 
    stok: 140, 
    initialStok: 140, 
    image: "/img/sayur/daun-gingseng.jpg" },
  { 
    id: 38,
    name: "Daun Mint", 
    deskripsi: "Daun Mint adalah sayuran yang memiliki aroma segar dan sering digunakan dalam minuman atau hidangan penutup.", 
    category: "Sayur", 
    displayPrice: "30.00", 
    price: 3000, 
    rate: '4.4', 
    isFav: false, 
    stok: 150, 
    initialStok: 150, 
    image: "/img/sayur/daun-mint.jpg" },
  { 
    id: 39,
    name: "Daun Salam", 
    deskripsi: "Daun Salam adalah sayuran yang digunakan sebagai bumbu dalam masakan dengan aroma khas.", 
    category: "Sayur", 
    displayPrice: "32.00", 
    price: 3200, 
    rate: '3.3', 
    isFav: false, 
    stok: 160, 
    initialStok: 160, 
    image: "/img/sayur/daun-salam.jpg" },
  { 
    id: 40,
    name: "Daun Siomak", 
    deskripsi: "Daun Siomak adalah sayuran yang digunakan dalam pembungkusan makanan seperti lumpia atau siomay.", 
    category: "Sayur", 
    displayPrice: "34.00", 
    price: 3400, 
    rate: '4.6', 
    isFav: false, 
    stok: 170, 
    initialStok: 170, 
    image: "/img/sayur/daun-siomak.jpg" },
  { 
    id: 41,
    name: "Jagung", 
    deskripsi: "Jagung adalah sayuran dengan biji-bijian yang manis dan sering digunakan dalam hidangan seperti sup atau bakar.", 
    category: "Sayur", 
    displayPrice: "36.00", 
    price: 3600, 
    rate: '4.5', 
    isFav: false, 
    stok: 180, 
    initialStok: 180, 
    image: "/img/sayur/Jagung.jpg" },
  { 
    id: 42,
    name: "Jahe", 
    deskripsi: "Jahe adalah sayuran yang memiliki rasa pedas dan aroma khas serta memiliki banyak manfaat kesehatan.", 
    category: "Sayur", 
    displayPrice: "38.00", 
    price: 3800, 
    rate: '4.4', 
    isFav: false, 
    stok: 190, 
    initialStok: 190, 
    image: "/img/sayur/Jahe.jpg" },
  { 
    id: 43,
    name: "Jeruk Nipis", 
    deskripsi: "Jeruk Nipis adalah sayuran yang memiliki rasa asam segar dan sering digunakan dalam masakan atau minuman.", 
    category: "Sayur", 
    displayPrice: "40.00", 
    price: 4000, 
    rate: '4.7', 
    isFav: false, 
    stok: 200, 
    initialStok: 200, 
    image: "/img/sayur/jeruk-nipis.jpg" },
  { 
    id: 44,
    name: "Kacang Panjang", 
    deskripsi: "Kacang Panjang adalah sayuran yang memiliki biji panjang dan sering digunakan dalam hidangan tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "42.00", 
    price: 4200, 
    rate: '4.6', 
    isFav: false, 
    stok: 50, 
    initialStok: 50, 
    image: "/img/sayur/kacang-panjang.jpg" },
  { 
    id: 45,
    name: "Kailan", 
    deskripsi: "Kailan adalah sayuran hijau yang sering digunakan dalam hidangan masakan Tionghoa.", 
    category: "Sayur", 
    displayPrice: "44.00", 
    price: 4400, 
    rate: '4.3', 
    isFav: false, 
    stok: 60, 
    initialStok: 60, 
    image: "/img/sayur/Kailan.jpg" },
  { 
    id: 46,
    name: "Kangkung", 
    deskripsi: "Kangkung adalah sayuran hijau yang sering digunakan dalam hidangan tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "46.00", 
    price: 4600, 
    rate: '4.5', 
    isFav: false, 
    stok: 70, 
    initialStok: 70, 
    image: "/img/sayur/Kangkung.jpg" },
  { 
    id: 47,
    name: "Kembang Kol", 
    deskripsi: "Kembang Kol adalah sayuran yang memiliki bentuk menyerupai bunga dan sering digunakan dalam hidangan seperti tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "48.00", 
    price: 4800, 
    rate: '4.4', 
    isFav: false, 
    stok: 80, 
    initialStok: 80, 
    image: "/img/sayur/kembang-kol.jpg" },
  { 
    id: 48,
    name: "Kentang", 
    deskripsi: "Kentang adalah sayuran dengan tekstur yang lembut dan sering digunakan dalam hidangan seperti kentang goreng atau puree.", 
    category: "Sayur", 
    displayPrice: "50.00", 
    price: 5000, 
    rate: '4.7', 
    isFav: false, 
    stok: 90, 
    initialStok: 90, 
    image: "/img/sayur/Kentang.jpg" },
  { 
    id: 49,
    name: "Labu Siam", 
    deskripsi: "Labu Siam adalah sayuran yang memiliki tekstur renyah dan sering digunakan dalam hidangan seperti sup atau tumis.", 
    category: "Sayur", 
    displayPrice: "52.00", 
    price: 5200, 
    rate: '4.6', 
    isFav: false, 
    stok: 100, 
    initialStok: 100, 
    image: "/img/sayur/labu-siam.jpg" },
  { 
    id: 50,
    name: "Lengkuas", 
    deskripsi: "Lengkuas adalah sayuran dengan aroma khas dan sering digunakan sebagai bumbu dalam masakan.", 
    category: "Sayur", 
    displayPrice: "54.00", 
    price: 5400, 
    rate: '4.3', 
    isFav: false, 
    stok: 110, 
    initialStok: 110, 
    image: "/img/sayur/Lengkuas.jpg" },
  { 
    id: 51,
    name: "Lobak", 
    deskripsi: "Lobak adalah sayuran dengan rasa segar dan sering digunakan dalam hidangan seperti salad atau acar.", 
    category: "Sayur", 
    displayPrice: "56.00", 
    price: 5600, 
    rate: '3.5', 
    isFav: false, 
    stok: 120, 
    initialStok: 120, 
    image: "/img/sayur/Lobak.jpg" },
  { 
    id: 52,
    name: "Oregano", 
    deskripsi: "Oregano adalah sayuran dengan aroma dan rasa yang khas serta sering digunakan sebagai bumbu dalam masakan Italia.", 
    category: "Sayur", 
    displayPrice: "58.00", 
    price: 5800, 
    rate: '4.4', 
    isFav: false, 
    stok: 130, 
    initialStok: 130, 
    image: "/img/sayur/Oregano.jpg" },
  { 
    id: 53,
    name: "Pak Choy", 
    deskripsi: "Pak Choy adalah sayuran hijau yang sering digunakan dalam hidangan masakan Asia.", 
    category: "Sayur", 
    displayPrice: "60.00", 
    price: 6000, 
    rate: '4.7', 
    isFav: false, 
    stok: 140, 
    initialStok: 140, 
    image: "/img/sayur/pak-choy.jpg" },
  { 
    id: 54,
    name: "Paprika Merah", 
    deskripsi: "Paprika Merah adalah sayuran yang memiliki rasa manis dan sering digunakan dalam masakan atau salad.", 
    category: "Sayur", 
    displayPrice: "62.00", 
    price: 6200, 
    rate: '4.6', 
    isFav: false, 
    stok: 150, 
    initialStok: 150, 
    image: "/img/sayur/paprika-merah.jpg" },
  { 
    id: 55,
    name: "Pare", 
    deskripsi: "Pare adalah sayuran yang memiliki rasa pahit dan sering digunakan dalam hidangan tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "64.00", 
    price: 6400, 
    rate: '4.3', 
    isFav: false, 
    stok: 160, 
    initialStok: 160, 
    image: "/img/sayur/Pare.jpg" },
  { 
    id: 56,
    name: "Radish", 
    deskripsi: "Radish adalah sayuran dengan rasa pedas dan sering digunakan dalam hidangan seperti salad atau acar.", 
    category: "Sayur", 
    displayPrice: "66.00", 
    price: 6600, 
    rate: '4.5', 
    isFav: false, 
    stok: 170, 
    initialStok: 170, 
    image: "/img/sayur/Radish.jpg" },
  { 
    id: 57,
    name: "Sawi Hijau", 
    deskripsi: "Sawi Hijau adalah sayuran hijau yang sering digunakan dalam hidangan tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "68.00", 
    price: 6800, 
    rate: '3.4', 
    isFav: false, 
    stok: 180, 
    initialStok: 180, 
    image: "/img/sayur/sawi-hijau.jpg" },
  { 
    id: 58,
    name: "Selada Romain", 
    deskripsi: "Selada Romain adalah sayuran hijau yang sering digunakan dalam hidangan salad.", 
    category: "Sayur", 
    displayPrice: "70.00", 
    price: 7000, 
    rate: '4.7', 
    isFav: false, 
    stok: 190, 
    initialStok: 190, 
    image: "/img/sayur/selada-romain.jpg" },
  { 
    id: 59,
    name: "Seledri", 
    deskripsi:"Seledri adalah sayuran dengan aroma khas dan sering digunakan sebagai bumbu dalam masakan atau sebagai garnis.", 
    category: "Sayur", 
    displayPrice: "72.00", 
    price: 7200, 
    rate: '4.6', 
    isFav: false, 
    stok: 200, 
    initialStok: 200, 
    image: "/img/sayur/Seledri.jpg" },
  { 
    id: 60,
    name: "Sereh", 
    deskripsi: "Sereh adalah sayuran dengan aroma harum dan sering digunakan sebagai bumbu dalam masakan.", 
    category: "Sayur", 
    displayPrice: "74.00", 
    price: 7400, 
    rate: '4.3', 
    isFav: false, 
    stok: 50, 
    initialStok: 50, 
    image: "/img/sayur/Sereh.jpg" },
  { 
    id: 61,
    name: "Tahu", 
    deskripsi: "Tahu adalah sayuran dengan tekstur lembut dan sering digunakan dalam hidangan seperti tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "76.00", 
    price: 7600, 
    rate: '4.5', 
    isFav: false, 
    stok: 60, 
    initialStok: 60, 
    image: "/img/sayur/Tahu.jpg" },
  { 
    id: 62,
    name: "Tempe", 
    deskripsi: "Tempe adalah sayuran yang memiliki rasa pedas dan sering digunakan dalam hidangan seperti sambal atau masakan khas Indonesia.", 
    category: "Sayur", 
    displayPrice: "78.00", 
    price: 7800, 
    rate: '4.4', 
    isFav: false, 
    stok: 70, 
    initialStok: 70, 
    image: "/img/sayur/tempe.jpg" },
  { 
    id: 63,
    name: "Terong Ungu", 
    deskripsi: "Terong Ungu adalah sayuran dengan warna ungu yang menarik dan sering digunakan dalam hidangan tumis atau sup.", 
    category: "Sayur", 
    displayPrice: "80.00", 
    price: 8000, 
    rate: '3.7', 
    isFav: false, 
    stok: 80, 
    initialStok: 80, 
    image: "/img/sayur/terong-ungu.jpg" },
  { 
    id: 64,
    name: "Timun", 
    deskripsi: "Timun adalah sayuran yang memiliki rasa segar dan sering digunakan dalam hidangan salad atau sebagai acar.", 
    category: "Sayur", 
    displayPrice: "82.00", 
    price: 8200, 
    rate: '4.6', 
    isFav: false, 
    stok: 90, 
    initialStok: 90, 
    image: "/img/sayur/Timun.jpg" },
  { 
    id: 65,
    name: "Toge", 
    deskripsi: "Toge adalah sayuran yang memiliki tekstur renyah dan sering digunakan dalam hidangan seperti pecel atau lalapan.", 
    category: "Sayur", 
    displayPrice: "84.00", 
    price: 8400, 
    rate: '4.3', 
    isFav: false, 
    stok: 100, 
    initialStok: 100, 
    image: "/img/sayur/toge.jpg" },
  { 
    id: 66,
    name: "Ubi", 
    deskripsi: "Ubi adalah sayuran dengan rasa manis dan sering digunakan dalam hidangan seperti kue atau olahan panggang.", 
    category: "Sayur", 
    displayPrice: "86.00", 
    price: 8600, 
    rate: '4.5', 
    isFav: false, 
    stok: 110, 
    initialStok: 110, 
    image: "/img/sayur/ubi.png" },
  { 
    id: 67,
    name: "Wortel", 
    deskripsi: "Wortel adalah sayuran yang memiliki warna oranye cerah dan sering digunakan dalam hidangan seperti sup atau tumis.", 
    category: "Sayur", 
    displayPrice: "88.00", 
    price: 8800, 
    rate: '4.4', 
    isFav: false, 
    stok: 120, 
    initialStok: 120, 
    image: "/img/sayur/Wortel.jpg" 
  }
]
const productsLimit = []

for(let i = 0; i < 10; i++) {
  productsLimit.push(products[i])
}

function randomComparator() {
  return Math.random() - 0.5;
}

const initialState = {
  allProducts: products.sort(randomComparator),
  productsLimit: productsLimit,
}

export const productsSlice = createSlice({
  name: 'products',
  initialState,
  reducers: {

  }
})

// export const {} = productsSlice.actions
export default productsSlice.reducer